### ISSUE TITLE
single node install sshd problem

### ISSUE THREAD

**Issue by chukynax** [lae/ansible-role-proxmox#127]
once i started to play role for my node, after it get rebooted i couldn't access server because of sshd changed policy and blocked everything even machine with ansible

**Comment by trickert76** [comment]
Do you know, what sshd config is changed? 

Because - the only thing, I know about is, that the role adds in cluster mode all other Host-keys and adds ssh-authorized-keys for root user. So root on host A can go with his ssh-user-key to host B inside the cluster without password. See ssh_cluster_config.yml

So - there is no change in the SSH config itself that should prevent you from logging in from you ansible controller.

If `pve_manage_ssh` is false - the role will not change anything on the host. 
If you run ssh on none default port 22 and not changed `pve_ssh_port`then you will - of course need to reconfigure that.

**Comment by lae** [comment]
Given this is on a single node, `pve_cluster_enabled` is probably not enabled, so no changes should be occurring as a result of this role.

@chukynax Please post what you have set your role variables to, as well as the playbook you are running and any other roles you may be running. And are you deploying to a bare Debian host?

**Comment by lae** [comment]
Closing due to lack of information. Please reopen, providing context requested above, if you're still having issues.
