### ISSUE TITLE
galaxy role is not working

### ISSUE THREAD

**Issue by artemoz2021** [lae/ansible-role-proxmox#137]
Hello.
I'm using the latest version of lae.proxmox role via ansible galaxy (1.6.8) and got the following error:

```
TASK [lae.proxmox : Remove subscription check wrapper function in web UI] ************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PatchError: 1 out of 3 hunks FAILED
fatal: [<host>]: FAILED! => changed=false 
  msg: |-
    1 out of 3 hunks FAILED

```

Can you fix this please?

**Comment by lae** [comment]
This was fixed two days ago, I believe. I just haven't pushed out a release yet. You can grab the development version with:

```
ansible-galaxy install -f https://github.com/lae/ansible-role-proxmox/archive/develop.tar.gz,develop,lae.proxmox
```

(and once a release is cut you can just force update it from galaxy directly. I'll probably get around to it soon, hopefully.)

**Comment by artemoz2021** [comment]
Ok, thank you!

**Comment by openmsk** [comment]
not working now

**Comment by liambresnahan** [comment]
this is also not working here. When trying to apply the patch directly I get:

`:~$ sudo patch < 00_remove_checked_command_buster.patch`
```patching file proxmoxlib.js
Hunk #1 FAILED at 459.
1 out of 1 hunk FAILED -- saving rejects to file proxmoxlib.js.rej```

**Comment by jmariondev** [comment]
proxmoxlib.js probably changed upstream, this feature is actually pretty fragile.

You can workaround this issue by setting `pve_remove_subscription_warning` to false.

**Comment by lae** [comment]
The `pve_remove_subscription_warning` role variable was introduced to keep it from being a showstopper, really. I've been hesitant to set `ignore_errors` on that task because for the longest time Travis CI would actually catch when proxmoxlib.js changed upstream, I'd then get a notification for a failed build, and then I could update the patch in a relatively short time frame. But lately I haven't really managed to react to failed builds (not to mention it seems like travis-ci.org shutdown and so this role isn't actively being tested anymore)...

Anyway, as an extension to #139 given how simple the patch now is, I think we could actually just replace the task with a `lineinfile`? Doesn't eliminate breakage entirely but my assumption is that it should work until upstream does a massive overhaul or something.

**Comment by lae** [comment]
#172 takes care of the idea I mentioned in the last post. I don't think there's anything left to discuss here, so closing.
