### ISSUE TITLE
[Proxmox 5.2] Error when configuring cluster

### ISSUE THREAD

**Issue by bozho** [lae/ansible-role-proxmox#40]
Hi,

I'm testing your role for provisioning Proxmox nodes in a cluster and I believe I ran into a bug. I am testing this by installing a Debian 9.5 on Hyper-V and then running the role.

The task `[lae.proxmox : Lookup cluster information]` fails with the following error:
```
fatal: [node-test.home]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 172.26.245.157 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_PYjZHK/ansible_module_proxmox_query.py\", line 70, in <module>\r\n    main()\r\n  File \"/tmp/ansible_PYjZHK/ansible_module_proxmox_query.py\", line 60, in main\r\n
result['response'] = pvesh.get(module.params['query'])\r\n  File \"/tmp/ansible_PYjZHK/ansible_modlib.zip/ansible/module_utils/pvesh.py\", line 69, in get\r\n  File \"/tmp/ansible_PYjZHK/ansible_modlib.zip/ansible/module_utils/pvesh.py\", line 32, in run_command\r\nIndexError: list index out of range\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

The error is in `pvesh.py` line 32:
```
    if stderr[0] == "200 OK":
```

Running the `pvesh` query manually on the node:
```
pvesh get cluster/status --output-format json
```

gives:
```
[{"id":"node/node-test","ip":"172.26.245.157","level":"","local":1,"name":"node-test","nodeid":0,"online":1,"type":"node"}]
```
and no stderr output, while `pvesh.py` code expects a `200 OK`.

**Comment by lae** [comment]
@bozho this bug was fixed about 2 weeks ago, but wasn't tagged/released because I was expecting some more breaking changes upstream in the proxmox CLI library (which seemed to have been pushed to repositories yesterday) and because the development branch isn't currently in a state I can easily release a patch for 1.4.x due to #33 (and there are some more pending issues to complete before a 1.5.0 release).

You should be able to install the development version of this role with the following for the time being:

    ansible-galaxy install https://github.com/lae/ansible-role-proxmox/archive/develop.tar.gz,develop,lae.proxmox

I would expect to get the next release out within the coming 2 weeks.

**Comment by bozho** [comment]
@lae thank you for a quick response. No rush, I'll play around with the dev version.

**Comment by Insoleet** [comment]
Hello,

I'm encountering the same issue. Should I also use the dev version ?

**Comment by lae** [comment]
@Insoleet Hi, yes, please use the version off current develop.

**Comment by lae** [comment]
Since it didn't quite hit me how critical a bug this was (heh) and the pending issues I had open in the 1.5.0 milestone were actually just feature requests, I went ahead and pushed those back/cut a 1.5.0 release off develop.
