### ISSUE TITLE
Package upgrades should be dist-upgrades

### ISSUE THREAD

**Issue by redmop** [lae/ansible-role-proxmox#70]
As per: https://pve.proxmox.com/wiki/System_Software_Updates

tasks/main.yml line 82

- name: Perform system upgrades
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: **dist**
  when: "pve_run_system_upgrades | bool"
  retries: 2
  register: _system_upgrade

**Comment by lae** [comment]
Hm, I guess this is probably preventing kernel updates? Apart from kernel updates, are you seeing any other packages being held back for updates other than the kernel?

I'm thinking that we might want to keep this as-is and introduce another step to perform kernel/dist upgrades so that people can still update Proxmox online for minor releases/security fixes but save updates to the kernel for when reboots are possible.

**Comment by redmop** [comment]
"apt dist-upgrade" is required to get any kind of support from them. "apt upgrade" is not supported. That's why I bring it up. There are many posts on the forum confirming this.

**Comment by lae** [comment]
I'm not sure how that runs counterpoint to my suggestion. I'm not privy to any conversations on the forum on the perils of `apt upgrade` vs `apt dist-upgrade`, nor could I find any cases indicating that people who ran `apt upgrade` ever were denied support with a few minutes of searching on Google, so if you could link a specific one (or multiple), it would help.

To rephrase what I said earlier, we would just split off `dist-upgrade` as another opt-in instead of changing the behaviour of the existing role variable (a change some users of the role may not want in the first place). If there are actually cases where people have ran `apt upgrade` first and then `dist-upgrade` and proceeded to be denied support, I guess we can set it to `dist-upgrade` by default. (If anyone else has thoughts on this, feel free to pitch in.)

**Comment by redmop** [comment]
https://forum.proxmox.com/threads/upgrade-issues.32727/

It's a good start.

**Comment by lae** [comment]
kk, fabian's post (10th in the thread) there helps explain their packaging procedure. I'll include this change in the next minor release.

**Comment by redmop** [comment]
Awesome. Thanks. :)
