### ISSUE TITLE
Ceph init should include possibility to add replication network

### ISSUE THREAD

**Issue by mholasek** [lae/ansible-role-proxmox#72]
We need the ability to create ceph with different public and replication networks.
I miss an option to define ```--cluster-network <string>```.

I would create a variable to define cluster-network and if this cluster network is defined, this option should be added.

Something like that:
```yaml
  command: 'pveceph init --network {{ pve_ceph_network }} --cluster-network {{ pve_ceph_cluster_network }}' 
```

**Comment by mholasek** [comment]
I can do and test this with pullrequest on weekend. Very simple enhancement.

```yaml
command: 'pveceph init --network {{ pve_ceph_network }} 
{% if pve_ceph_cluster_network is defined  %} \
            --cluster-network {{ pve_ceph_cluster_network }}'
{% endif %}"
```

**Comment by lae** [comment]
That would be appreciated. Do you think you could test this with #69 as a base (instead of `develop`), actually?

**Comment by mholasek** [comment]
> That would be appreciated. Do you think you could test this with #69 as a base (instead of `develop`), actually?

sure, I'll do.

**Comment by mholasek** [comment]
I finished this issue and testing the other #69 (took some time to prepare my bare metal cluster that I am going to install). I have some problems regarding idempodent creation of osd. The role stops if an osd is already in use.

@lae  Should we check, if a defined OSD is already in use and move on with the other tasks?

Example:
I had some timeout during OSD creation and it was necessary to repeat the playbook. The OSD's were created properly but the execution stops after OSD creation. Role does not create pools and storages at this stage.

**Comment by lae** [comment]
yes - I'm unfortunately not able to test idempotency of that part myself (no longer working at fireeye/don't have access to a lot of physical hardware anymore) and CI can't either. All tasks should be made idempotent.

I'm not sure if you can just use a `creates` argument on the OSD creation step (because iirc OSD creation picks a random number for the folder name) but maybe you could add another task before the creation step to check if there is an existing OSD associated with the selected drive, and then skip OSD creation/configuration tasks based on the result?

**Comment by mholasek** [comment]
Creating another task checking the osd's is what I had in mind. I'll include the changes in my feature branch, should be available within a few days.

**Comment by lae** [comment]
@mholasek What's some example JSON output from that command once you get a successful OSD provisioned with `pveceph`? ([docs](https://docs.ceph.com/docs/master/ceph-volume/lvm/list/) show that you can use `--format=json`) Just to confirm, the `lvm list` command doesn't have anything to do with Linux LVM, right? (In other words, this command should be appropriate for checking provisioned OSDs in all deployment scenarios with pveceph?) If that's the case, we could possibly create a small Ansible module for OSD creation without needing to write any parsing code.

So I had forgotten earlier, but I believe `{device}1` was selected on the basis that the `pveceph osd create` command creates a partition on the device, and that was picked instead of something like `/var/lib/ceph/osd-5` (which is what I was referring to in my previous comment) to keep the OSD creation step idempotent. (For mutual reference, you're referring to [this line](https://github.com/lae/ansible-role-proxmox/blob/v1.6.1/tasks/ceph.yml#L66), right? So it's not necessarily `/dev/sd?1`, unless you're finding that somewhere else?) The `pveceph` tool expects the devices passed to be one the patterns listed in [this comment](https://github.com/lae/ansible-role-proxmox/pull/52#issuecomment-483853661), at least in PVE5. Are you trying with something different? (maybe you could check if that code is any different in PVE6?)

**Comment by lae** [comment]
If you could, can you split off the replication network changes into a single PR (those changes look fine to me), and then we can look further at the OSD creation steps? Since it's a bit off-topic, I moved those comments to #73.
